//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobApplicant
    {
        public int JobApplicantId { get; set; }
        public Nullable<int> JobSeekerId { get; set; }
        public Nullable<int> JobId { get; set; }
        public Nullable<bool> AppliedForJob { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual JobSeeker JobSeeker { get; set; }
    }
}
