//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobSeeker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobSeeker()
        {
            this.JobApplicants = new HashSet<JobApplicant>();
        }
    
        public int JobSeekerId { get; set; }
        public Nullable<int> UserAccountId { get; set; }
        public string JobTitle { get; set; }
        public Nullable<int> ExperienceLevelId { get; set; }
        public Nullable<bool> SeekingWork { get; set; }
        public Nullable<bool> AvailableNow { get; set; }
        public string Bio { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobApplicant> JobApplicants { get; set; }
        public virtual UserAccount UserAccount { get; set; }
        public virtual ExperienceLevel ExperienceLevel { get; set; }
        
    }
}
